function areaVec = pcryAreaVoronoi(v,c)
%AREAVORONOI Takes the Voronoi tesellation generated by the voronoin matlab
%function and uses it to calculate the areas of the cells.
%   Both parameters (v,c) are automatically generated by the function
%   voronoi over a set of points. 
%       v:              vertices
%       c:              cell array indicating the vertices corresponding to 
%                       each cell
    
    % Determine the number of cells to process
    numCells = length(c);
    areaVec = zeros(numCells,1);

    for i = 1:numCells
        % Get the vertices of the current cell
        x = v(c{i},1);
        y = v(c{i},2);

        areaVec(i) = polyarea(x,y);
    end
end